name = "falling-cell-3243"
main = "src/index.ts"
compatibility_date = "2025-07-10"

[vars]
appVersion = "1.6.0"

[observability.logs]
enabled = true

[durable_objects]
bindings = [
	{ name = "PARTY_STATE", class_name = "GamePartyState" },
	{ name = "TRACKER", class_name = "Tracker" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PartyState"]

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "PartyState", to = "GamePartyState" }]

# Add the Tracker DO in a new migration
[[migrations]]
tag = "v3"
new_classes = ["Tracker"]

[[d1_databases]]
binding = "DB"
database_name = "web-games-d1-db-wu"
database_id = "5ad83906-a7bd-4fee-bef8-c19195b6f984"
