name = "falling-cell-3243"
main = "src/index.ts"
compatibility_date = "2025-07-10"

[durable_objects]
bindings = [{ name = "PARTY_STATE", class_name = "PartyState" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "PartyState" ]
